import variants from '@/data/image-variants.json';

/**
 * Widths available per image, generated by scrape/optimize-images.mjs.
 * Post cards render at roughly 380px but were shipping the full 1200px file.
 *
 * Static import rather than readFileSync(process.cwd()) — the same pattern in
 * app/sitemap.ts threw at request time on Hostinger, where the working directory
 * differs from the build. Inlined at build time, this cannot fail at runtime.
 */
const VARIANTS = variants as Record<string, number[]>;

/** Intrinsic width of the base file, so the largest srcset candidate is honest. */
const BASE_WIDTH = 1200;

export default function CardImage({
  src,
  alt,
  className = '',
  sizes = '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 380px',
  priority = false,
}: {
  src: string;
  alt: string;
  className?: string;
  sizes?: string;
  priority?: boolean;
}) {
  const widths = VARIANTS[src];
  const srcSet = widths
    ? [...widths.map((w) => `${src.replace(/\.webp$/, `-${w}w.webp`)} ${w}w`), `${src} ${BASE_WIDTH}w`].join(', ')
    : undefined;

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      {...(srcSet ? { srcSet, sizes } : {})}
      alt={alt}
      width={640}
      height={360}
      className={className}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      {...(priority ? { fetchPriority: 'high' as const } : {})}
    />
  );
}
